"""date2

Revision ID: 0482c9d51cc6
Revises: 4b04b11cb26e
Create Date: 2026-03-19 14:07:14.071577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0482c9d51cc6'
down_revision: Union[str, Sequence[str], None] = '4b04b11cb26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Изменяем created_at в deliveries
    op.alter_column('deliveries', 'created_at',
                    type_=sa.Date(),
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    postgresql_using='created_at::date')  # для PostgreSQL

    # Изменяем timestamp в redirections
    op.alter_column('redirections', 'timestamp',
                    type_=sa.Date(),
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    postgresql_using='timestamp::date')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
