"""Operations

Revision ID: 40a064bae9a9
Revises: c65db1305a20
Create Date: 2026-02-23 03:08:56.027297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a064bae9a9'
down_revision: Union[str, Sequence[str], None] = 'c65db1305a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_items.id'], ),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pvz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_items.id'], name=op.f('operation_delivery_item_id_fkey')),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvz.id'], name=op.f('operation_pvz_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('operation_pkey'))
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
