"""remove unique constraint from deliveries.pvz_id

Revision ID: 41717eea7087
Revises: 2696770c21cf
Create Date: 2026-02-23 00:55:27.524812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41717eea7087'
down_revision: Union[str, Sequence[str], None] = '2696770c21cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deliveries_pvz_id_key'), 'deliveries', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('deliveries_pvz_id_key'), 'deliveries', ['pvz_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
