"""Operations

Revision ID: c65db1305a20
Revises: 41717eea7087
Create Date: 2026-02-23 03:03:58.417681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65db1305a20'
down_revision: Union[str, Sequence[str], None] = '41717eea7087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('pvz_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_items.id'], ),
    sa.ForeignKeyConstraint(['pvz_id'], ['pvz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    # ### end Alembic commands ###
