"""add redirections table

Revision ID: cf9ea757e109
Revises: 20efdc0ce2d4
Create Date: 2026-03-02 12:07:24.648179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9ea757e109'
down_revision: Union[str, Sequence[str], None] = '20efdc0ce2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('old_delivery_id', sa.Integer(), nullable=False),
    sa.Column('new_delivery_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_items.id'], ),
    sa.ForeignKeyConstraint(['new_delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['old_delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirections_id'), 'redirections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirections_id'), table_name='redirections')
    op.drop_table('redirections')
    # ### end Alembic commands ###
